#!/bin/bash

# GitHub Pages Setup Helper
# Guides user through fixing deployment issues

echo "🔧 GitHub Pages Deployment Troubleshooting"
echo "=========================================="
echo ""

echo "The build succeeded but deploy failed. This usually means:"
echo ""
echo "📋 REQUIRED REPOSITORY SETTINGS:"
echo ""
echo "1. Go to your repository on GitHub:"
echo "   https://github.com/Elghazawy5367/Council-Git-V9/settings/pages"
echo ""
echo "2. Under 'Build and deployment', set:"
echo "   Source: GitHub Actions (NOT 'Deploy from a branch')"
echo ""
echo "3. Click 'Save'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📸 VISUAL GUIDE:"
echo ""
echo "  Source dropdown should show:"
echo "  ┌─────────────────────────────┐"
echo "  │ ○ Deploy from a branch      │"
echo "  │ ● GitHub Actions     ← SELECT THIS"
echo "  └─────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After changing the setting:"
echo ""
echo "  Option A) Re-run the failed workflow:"
echo "    1. Go to: https://github.com/Elghazawy5367/Council-Git-V9/actions"
echo "    2. Click on the failed workflow run"
echo "    3. Click 'Re-run all jobs'"
echo ""
echo "  Option B) Push a new commit:"
echo "    The updated workflow will auto-trigger"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 VERIFY SETTINGS:"
echo ""
echo "Run this command to check if Pages is configured:"
echo "  curl -s https://api.github.com/repos/Elghazawy5367/Council-Git-V9/pages"
echo ""
echo "If you see an error, Pages hasn't been enabled yet."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ ONCE FIXED:"
echo ""
echo "Your site will be live at:"
echo "  https://elghazawy5367.github.io/Council-Git-V9/"
echo ""
echo "Deployment typically takes 1-2 minutes after the workflow succeeds."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
